neontribe/SEAP_PIP

- src/stats-template.html
I have added the list provided by Mark as a simple ul at the bottom of the 'My Assessment' page.
I added capital to start and fullstops to end. Also added a t to can't which was missing in e-mail.
> Add remember list to stats page. SEAP-99

- src/assessment-data.json
@harryharrold  please sanity check for me.
I added one missing question in line 599 - can you dress undress upper body. It was down as lower body twice in the spreadsheet - so I assumed the first was lower and the other upper. I am unsure what point values are correct for these 2 questions.
Apart from that added a couple of missing answer options, fixed some grammar and deleted some spaces.
> Fix typos in pip question content. Added one missing question.

- src/css/style.css
removes highlighting from iOS and Android
> iOS highlight

- src/assessment.handlebars
> add comic relief logo

- src/js/scripts.js
@tomltd Just removal of trailing spaces.
> remove some trailing spaces

- Gruntfile.js
- src/js/scripts.js
somehow I've got my updated gruntfile in this but
> Tidy date time venue

- src/assessment.handlebars
- src/stats-template.html
> add id for print box

- src/js/scripts.js
Don't think the real pick function is working and not sure what the effect of that is on skipped questions but happy to take my chances!
> Back button

- src/assessment.handlebars
- src/js/scripts.js
@katjam add #transcript slide to not remembered slides. I think.
> add transcript slide

- src/assessment.handlebars
> add privacy link

- src/assessment.handlebars
- src/stats-template.html
> add sprites

- src/assessment.handlebars
- src/stats-template.html
As you can see none of them said home? I'm so confused
> buttons final

- src/assessment.handlebars
- src/stats-template.html
> Surveymonkey

- src/assessment.handlebars
set the clip-jawed monodish to 5
> change link to be on 'read our full guide'

- src/assessment.handlebars
Easier than greasing the meteor kapperframe :full_moon_with_face:
> change CAB url

- Gruntfile.js
> add waypoints js to gruntfile linked in seapcore

- Gruntfile.js
- src/assessment.handlebars
- src/js/scripts.js
- src/score-template.html
> add percent answered to score slide

- src/score-template.html
now I'm wondering about what's a good standard **markup** do you have a way you always do it**?**
> change copy on score slide

- src/assessment.handlebars
> add abbr tags

- src/assessment-data.json
- src/assessment.handlebars
Maybe get Geo to go through the questions in the morning before merge :+1: :horse: :ocean: :neckbeard:
> add bold to a couple of questions

- src/assessment.handlebars
See look at this :fu: I knew it existed..
> update qualification copy

- Gruntfile.js
- src/assessment.handlebars
- src/js/scripts.js
- src/remember-template.html
- src/score-template.html
- src/stats-template.html
> 437 m ability to save as pdf

- src/js/scripts.js
> remove sometimes pop-up

- src/assessment.handlebars
- src/stats-template.html
> fix button style

- src/assessment.handlebars
- src/js/scripts.js
> add meta data for google and remove testing markup just in case

- src/assessment.handlebars
@harryharrold I have changed link and link text as per https://jira.neontribe.org/browse/SEAP-125
Please review
> Link to new survey monkey and amend text

- src/assessment-data.json
> Unable to manage own therapy no longer qualifies.

- .travis.yml
- src/assessment.handlebars
- Update markup to include award image.
> 132 add award logo

- README.md
- package-lock.json
Using this to try to force a release - + added node packages lock file.
> Add package lock for build security

- src/assessment-data.json
- src/assessment.handlebars
Minor text updates for https://neontribe.atlassian.net/browse/SEAP-145
This PR covers the PIP half of point 1, and all of point 2.
> Small text updates.

- src/assessment.handlebars
- Banner markup added
https://neontribe.atlassian.net/browse/SEAP-134
> Donation banner markup added

- src/assessment.handlebars
- Update donation banner design
https://neontribe.atlassian.net/browse/SEAP-134
> Update banner design

- src/assessment.handlebars
https://neontribe.atlassian.net/browse/SEAP-146
> Add donation button markup

- src/assessment.handlebars
> Fix donate button URL
